version: 2

sphinx:
  configuration: docs/source/conf.py

formats: all

build:
  image: latest

python:
  version: "3.7"
  system_packages: true
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
