version: 2

sphinx:
  configuration: docs/source/conf.py
  fail_on_warning: false

formats: all

build:
  os: ubuntu-22.04
  tools:
    python: "mambaforge-22.9"

conda:
  environment: environment-dev.yml

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
