name: pavics-sdi
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python >=3.12,<3.14
  - aiohttp
  - birdy >=0.9.1
  - cartopy >=0.23.0
  - cf_xarray >=0.10.4
  - clisops >=0.16.1
  - dask >=2024.8.1
  - esgf-pyclient
  - fiona
  - furo >=2024.04.27
  - geopandas >=1.0
  - holoviews
  - hvplot
  - intake
  - intake-esm
  - ipyleaflet
  - ipython >=8.15.0
  - jinja2
  - jupyter
  - jupytext
  - matplotlib-base >=3.7.0
  - myst-nb
  - myst-parser
  - nbsphinx >=0.9.7
  - nbval
  - netcdf4
  - numba >=0.57.0
  - numpy >=1.25.0
  - owslib
  - pre-commit
  - psutil
  - pydap
  - pyogrio
  - pytest
  - readthedocs-sphinx-ext
  - recommonmark
  - requests
  - requests-magpie
  - shapely >=2.0
  - siphon
  - sphinx >=8.2.0
  - sphinx-codeautolink
  - sphinx-copybutton
  - sphinx-intl
  - sphinx-jsonschema
  - sphinxext-opengraph
  - urllib3
  - webob
  - xarray >=2023.11.0
  - xclim >=0.57.0
  - xesmf !=0.8.8
  - xscen >=0.12.1
  - xsdba >=0.5.0
  - pip
