name: pavics-sdi
channels:
  - conda-forge
  - defaults
dependencies:
  - pytest
  - jupyter
  - sphinx
  - sphinx_rtd_theme
  - nbsphinx
  - nbval
  - pip
  - pip:
    - sphinx-intl
    - sphinx-jsondomain # unmaintained and has sphinx <2.0 hardcoded in dependencies
    - sphinx-jsonschema
