name: pavics-sdi
channels:
  - conda-forge
  - defaults
dependencies:
  - python >=3.10,<3.11
  - cf_xarray
  - clisops
  - dask
  - esgf-pyclient
  - geopandas
  - intake
  - ipython
  - jinja2
  - jupyter
  - matplotlib
  - myst-nb
  - myst-parser
  - nbval
  - netcdf4
  - numba
  - owslib
  - pytest
  - requests
  - requests-magpie
  - sphinx
  - sphinx-codeautolink
  - sphinx-copybutton
  - sphinx-intl
  - sphinx-rtd-theme >=1.0
  - urllib3
  - urlpath
  - webob
  - xarray
  - xclim >=0.45.0
  - pip
