name: pavics-sdi
channels:
  - conda-forge
dependencies:
  - python >=3.10,<3.11
  - aiohttp
  - birdy
  - cartopy
  - cf_xarray
  - clisops >=0.15.0
  - dask
  - esgf-pyclient
  - fiona
  - geopandas >=1.0
  - holoviews
  - intake
  - intake-esm
  - ipyleaflet
  - ipython
  - jinja2
  - jupyter
  - jupytext
  - matplotlib
  - myst-nb
  - myst-parser
  - nbval
  - netcdf4
  - numba
  - numpy >=1.24.0
  - owslib
  - pre-commit
  - pyogrio
  - pytest
  - readthedocs-sphinx-ext
  - recommonmark
  - requests
  - requests-magpie
  - siphon
  - sphinx >=7.0.0,<8.2.0 # Python3.10 compatibility
  - sphinx-codeautolink
  - sphinx-copybutton
  - sphinx-intl
  - sphinx-jsonschema
  - sphinx-rtd-theme >=1.0
  - urllib3
  - webob
  - xarray
  - xclim >=0.45.0
  - xesmf
  - pip
