name: pavics-sdi
channels:
  - conda-forge
  - defaults
dependencies:
  - pytest
  - jupyter
  - pre-commit
  - sphinx
  - sphinx_rtd_theme
  - nbsphinx
  - nbval
  - pip
  - pip:
    - sphinx-intl
  - Jinja2<=3.0.3
