from setuptools import setup

CLASSIFIERS = [
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: BSD License",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3 :: 3.11",
    "Programming Language :: Python :: 3 :: 3.12",
    "Topic :: Scientific/Engineering :: Atmospheric Science",
]

setup(
    name="pavics_sdi",
    version="0.1",
    url="https://pavics-sdi.readthedocs.io",
    python_requires=">=3.10",
    install_requires=[],
    extras_require={
        "docs": [
            "aiohttp",
            "birdhouse-birdy",
            "cartopy >=",
            "cf-xarray >=0.10.4",
            "clisops >=0.16.1",
            "dask >=2024.8.1",
            "esgf-pyclient",
            "fiona",
            "furo >=2024.04.27",
            "geopandas >=1.0",
            "holoviews",
            "hvplot",
            "intake",
            "intake-esm",
            "ipyleaflet",
            "ipython >=8.15.0",
            "jinja2",
            "jupyter",
            "jupytext",
            "matplotlib >=3.7.0",
            "myst-nb",
            "myst-parser",
            "nbsphinx",
            "nbval",
            "netcdf4",
            "numba >=0.57.0",
            "numpy >=1.25.0",
            "owslib",
            "pydap",
            "psutil",
            "pyogrio",
            "readthedocs-sphinx-ext",
            "requests",
            "requests-magpie",
            "shapely >=2.0",
            "siphon",
            "sphinx-codeautolink",
            "sphinx-copybutton",
            "sphinx-intl",
            "sphinx-jsonschema",
            "sphinx >=8.2.0",
            "sphinxext-opengraph",
            "urllib3",
            "webob",
            "xarray >=2023.11.0",
            "xclim >=0.57.0",
            "xesmf !=0.8.8",
            "xscen >=0.12.1",
            "xsdba >=0.5.0",
        ]
    },
    author="CRIM/Ouranos",
    author_email="pavics@ouranos.ca",
    description="Scientific gateway for climate data analytics.",
    long_description=open("README.rst").read(),
    license="BSD",
    classifiers=CLASSIFIERS,
)
