from setuptools import setup

CLASSIFIERS = [
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: BSD License",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3 :: Only",
    "Topic :: Scientific/Engineering :: Atmospheric Science",
]

setup(
    name="pavics_sdi",
    version="0.1",
    url="https://pavics-sdi.readthedocs.io",
    install_requires=[],
    extras_require={
        "docs": [
            "birdhouse-birdy",
            "cartopy",
            "cf-xarray",
            "clisops",
            "dask",
            "esgf-pyclient",
            "geopandas",
            "holoviews",
            "intake",
            "intake-esm",
            "ipython",
            "jinja2",
            "jupyter",
            "jupytext",
            "matplotlib",
            "myst-nb",
            "myst-parser",
            "nbval",
            "netcdf4",
            "numba",
            "owslib",
            "pyogrio",
            "readthedocs-sphinx-ext",
            "requests",
            "requests-magpie",
            "sphinx-codeautolink",
            "sphinx-copybutton",
            "sphinx-intl",
            "sphinx-jsonschema",
            "sphinx-rtd-theme>=1.0",
            "sphinx>=1.4",
            "urllib3",
            "urlpath",
            "webob",
            "xarray",
            "xclim>=0.45.0",
            "xesmf",
        ]
    },
    author="CRIM/Ouranos",
    author_email="pavics@ouranos.ca",
    description="Scientific gateway for climate data analytics.",
    long_description=open("README.rst").read(),
    license="BSD",
    classifiers=CLASSIFIERS,
)
