name: Dagger/Docker Testing Suite

on:
  # FIXME: Remove Pull Request trigger before merging
  pull_request:
  schedule:
    # Every night at 4:00 AM UTC
    - cron: '0 4 * * *'
  workflow_dispatch:
    inputs:
      BASE_IMAGE_TAG:
        description: 'Image tag to use for the Docker image'
        required: true
      PAVICS_HOST:
        description: 'Pavics URL to test against'
        required: true
        default: 'https://pavics.ouranos.ca/'
      SANITIZE_FILE_URL:
        description: 'URL for the sanitizer configuration'
        required: true
        default: 'https://github.com/Ouranosinc/PAVICS-e2e-workflow-tests/raw/master/notebooks/output-sanitize.cfg'

concurrency:
  # For a given workflow, if we push to the same branch, cancel all previous builds on that branch except on main.
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

env:
  BASE_IMAGE_TAG: 230601

jobs:
  lint:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@002fdce3c6a235733a90a27c80493a3241e56863 # v2.12.1
        with:
          disable-sudo: true
          egress-policy: audit
      - name: Checkout Repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
      - name: Set up Python3
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: "3.x"
          cache: 'pip'
      - name: Run pre-commit
        uses: pre-commit/action@2c7b3805fd2a0fd8c1884dcaebf91fc102a13ecd # v3.0.1

  integration:
    name: Integration Tests (Python${{ matrix.python-version }})
    needs: lint
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      matrix:
        python-version: [ "3.10" ]
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@002fdce3c6a235733a90a27c80493a3241e56863 # v2.12.1
        with:
          disable-sudo: true
          egress-policy: audit
      - name: Checkout Repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
      - name: Set up Python3
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      - name: Set Environment Variables
        if: ${{ github.event_name != 'workflow_dispatch' }}
        run: |
          echo "BASE_IMAGE_TAG=${{ env.BASE_IMAGE_TAG }}" >> $GITHUB_ENV
      - name: Set Environment Variables (Workflow Dispatch)
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: |
          echo "BASE_IMAGE_TAG=${{ github.event.inputs.image_tag }}" >> $GITHUB_ENV
          echo "PAVICS_HOST=${{ github.event.inputs.PAVICS_HOST }}" >> $GITHUB_ENV
          echo "SANITIZE_FILE_URL=${{ github.event.inputs.SANITIZE_FILE_URL }}" >> $GITHUB_ENV
      - name: Dagger testing
        run: |
          pip install .[dagger]
          python ./CI/dagger-pipeline.py
